infer_config {
  unique_id: 1
  gpu_ids: 0
  max_batch_size: 1
  backend {
    triton {
      model_name: "dfine"
      version: -1
      model_repo {
        root: "./models"
        strict_model_config: true
      }
    }
    output_mem_type: MEMORY_TYPE_CPU
  }

  preprocess {
    network_format: IMAGE_FORMAT_RGB
    tensor_order: TENSOR_ORDER_NHWC
    tensor_name: "inputs"
    frame_scaling_hw: FRAME_SCALING_HW_DEFAULT
    frame_scaling_filter: 1
    symmetric_padding: 0
    maintain_aspect_ratio: 0
  }

  postprocess {
    labelfile_path: "./models/dfine/labels.txt"
    detection {
      num_detected_classes: 2
      custom_parse_bbox_func: "NvDsInferParseCustomDatature"
      nms: {
        confidence_threshold: 0.2
        iou_threshold: 0.3
        topk : 20
      }
    }
  }

  custom_lib {
    path: "./parser/libnvds_infercustomparser.so"
  }
}

input_control {
  process_mode: PROCESS_MODE_FULL_FRAME
  operate_on_gie_id: -1
  interval: 0
}
